---
login: "YOUR_USERNAME"
password: "YOUR_PASSWORD"

debug: 0
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"

tag_list: ["ì°½ì›", "ë§ˆì‚°", "ê²½ë‚¨", "ë§›ì§‘", "ìƒë‚¨ë™", "í•©ì„±ë™", "ê²½ë‚¨ëŒ€", "ëŒ“ê±°ë¦¬", "ì§„í•´", "ì„ íŒ”", "ë§íŒ”", "ì¸ìŠ¤íƒ€ê·¸ë¨"]
tag_blacklist: ["sex", "porno"]

like_per_day: 196
max_like_for_one_tag: 36
media_min_like: 20
media_max_like: 200
like_followers_per_run: 0

unlike_per_day: 0
time_till_unlike: 259200

follow_per_day: 156
follow_time: 259200
follow_attempts: 10
user_min_follow: 200
user_max_follow: 2200

unfollow_per_day: 199
unfollow_break_min: 3
unfollow_break_max: 17
unfollow_selebgram: false
unfollow_probably_fake: true
unfollow_inactive: true
unfollow_recent_feed: false
unfollow_whitelist: []

unwanted_username_list: ["free", "travel", "shop", "store", "sex", "online"]
comments_per_day: 0
comment_list: [
        ["ì•ˆë…•í•˜ì„¸ìš”!", "í”¼ë“œì˜ë´¤ì–´ìš”!", "í”¼ë“œëŒë‹¤ì™”ì–´ìš”ã…", "ìš°ì—°íˆ ë“¤ë ¸ì–´ìš”"],
        ["í”¼ë“œ ì¢‹ì•„ìš”~", "ì¹œí•˜ê²Œì§€ë‚´ìš©", "ã…!", "í•˜íŠ¸ëˆŒë €ì–´ìš”~", "íŒ”ë¡œí–ˆì–´ìš”"],
        ["ì¢‹ì€ í•˜ë£¨ ë˜ì„¸ìš”:)", "ì œ í”¼ë“œë„ ë†€ëŸ¬ì˜¤ì„¸ìš”ã…", "ë°˜ì‚¬ì˜¤ì„¸ìš”", "ğŸ˜Š", "ë§íŒ”í•´ìš”"],
        [
            "ğŸ™Œ",
            "ğŸ™",
            "ğŸ‘",
            "â­",
            "ğŸ",
            "ğŸ˜†",
            "ğŸ‘",
            "ğŸ‘‹",
            "ğŸ–",
            "ğŸˆ",
            "ğŸ“·",
            "ğŸ¤—",
        ],
        [".", "..", "...", "!", "!!", "!!!"],
    ]
